// ════════════════════════════════════════════════════════════
// ROUND 3 — TYPEWAVE (scrambled words, first to 5 wins)
// ════════════════════════════════════════════════════════════

let _ctx;
let btnTwStart; // referenced in both init() and renderHostTypewave()

// ✏️ EDIT YOUR TYPEWAVE WORDS HERE
const CUSTOM_WORDS = [
  // 🟢 EASY
  "pizza","cloud","flame","storm","blaze",
  "crisp","frost","grind","champ","chaos",
  // 🟡 MEDIUM
  "jungle","rocket","shadow","turbo","phantom",
  "bronze","galaxy","cobalt","magnet","spiral",
  // 🔴 HARD
  "avalanche","labyrinth","jellyfish","submarine","wolverine",
  "orchestra","carnival","helicopter","dinosaur","spectacular",
];

function _scrambleWord(w) {
  const a = w.toUpperCase().split('');
  let out, tries = 0;
  do {
    out = [...a];
    for (let i = out.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [out[i], out[j]] = [out[j], out[i]];
    }
    tries++;
  } while (out.join('') === a.join('') && tries < 20);
  return out.join('');
}

// Build word list at load time (scramble is generated by host and stored in Firebase)
const TYPEWAVE_WORDS = CUSTOM_WORDS.map(w => ({
  answer: w.toUpperCase(),
  _localScramble: _scrambleWord(w), // fallback only
}));

const TW_WORD_DURATION = 60; // seconds per word

// Host-side ephemeral typewave state
let twLocal = { resultApplied: false };
let twWordTimerTimeout = null; // host auto-advance timer

// Player-side: guards per-word so one correct submit can't fire twice
let twAnsweredThisWord  = false;
let twCurrentWordIndex  = -1;
let twClientTimerInterval = null; // client-side visual countdown

// ── Timer ring helper (player) ─────────────────────────────
function twUpdateTimerRing(secondsLeft) {
  const total = TW_WORD_DURATION;
  const fill  = document.getElementById('tw-ring-fill');
  const num   = document.getElementById('tw-timer-num');
  const ring  = document.getElementById('tw-timer-ring');
  if (!fill || !num) return;

  const circumference = 201; // 2π×32
  const offset = circumference * (1 - Math.max(0, secondsLeft) / total);
  fill.style.strokeDashoffset = offset;
  num.textContent = Math.max(0, secondsLeft);
  fill.classList.toggle('danger', secondsLeft <= 10);

  if (secondsLeft <= 0 && ring) {
    ring.classList.add('tw-timeout');
    setTimeout(() => ring?.classList.remove('tw-timeout'), 350);
  }
}

function twStartClientTimer(wordEndTime) {
  if (twClientTimerInterval) clearInterval(twClientTimerInterval);
  // Instantly snap ring to full before starting countdown (avoid slow fill animation)
  const fillEl = document.getElementById('tw-ring-fill');
  if (fillEl) {
    fillEl.style.transition = 'none';
    fillEl.style.strokeDashoffset = '0';
    void fillEl.offsetWidth; // force reflow
    fillEl.style.transition = '';
  }
  function tick() {
    const secondsLeft = Math.max(0, Math.min(TW_WORD_DURATION, Math.ceil((wordEndTime - Date.now()) / 1000)));
    twUpdateTimerRing(secondsLeft);
  }
  tick();
  twClientTimerInterval = setInterval(tick, 500);
}

function twStopClientTimer() {
  if (twClientTimerInterval) { clearInterval(twClientTimerInterval); twClientTimerInterval = null; }
  twUpdateTimerRing(TW_WORD_DURATION);
}

// ── Host: auto-advance after timer expires ─────────────────
async function twAdvanceWord(fromIndex) {
  twWordTimerTimeout = null;
  const nextIdx = fromIndex + 1;
  if (nextIdx >= TYPEWAVE_WORDS.length) {
    // Out of words — end round by score
    const scores = _ctx.getLatestRoundData()?.wordScores ?? { player1: 0, player2: 0 };
    const s1 = scores.player1 ?? 0, s2 = scores.player2 ?? 0;
    const winner = s1 > s2 ? 'player1' : s2 > s1 ? 'player2' : 'tie';
    try {
      await _ctx.update(_ctx.ref(_ctx.db, 'round'), { state: 'ended', winner });
    } catch(e) { console.error('[Typewave] end error', e); }
    return;
  }
  const word      = TYPEWAVE_WORDS[nextIdx];
  const scrambled = _scrambleWord(word.answer);
  const now       = Date.now();
  try {
    _ctx.flashTransition('var(--white)', 280);
    await _ctx.update(_ctx.ref(_ctx.db, 'round'), {
      wordIndex:     nextIdx,
      scrambled:     scrambled,
      correctAnswer: word.answer,
      wordWinner:    null,
      wordStartTime: now,
      wordEndTime:   now + TW_WORD_DURATION * 1000,
      timedOut:      false,
      lastAnswer:    { player1: null, player2: null },
    });
  } catch(e) { console.error('[Typewave] advance error', e); }
  // Set host auto-advance timeout
  twWordTimerTimeout = setTimeout(() => twAdvanceWord(nextIdx), TW_WORD_DURATION * 1000);
}

// ── Render: host typewave ──────────────────────────────────
export function renderHostTypewave(data, playersData) {
  if (!data || data.id !== 'typewave') return;

  const state      = data.state      ?? 'waiting';
  const wordIndex  = data.wordIndex  ?? 0;
  const wordScores = data.wordScores ?? { player1: 0, player2: 0 };
  const wrongCounts= data.wrongCounts?? { player1: 0, player2: 0 };
  const wordWinner = data.wordWinner ?? null;
  const lastAnswer = data.lastAnswer ?? {};

  const p1name = playersData?.player1?.name || 'Player 1';
  const p2name = playersData?.player2?.name || 'Player 2';

  // Names
  ['tw-sn1','tw-live-name-p1','tw-rmc-name-p1'].forEach(id => {
    const e = document.getElementById(id); if (e) e.textContent = p1name;
  });
  ['tw-sn2','tw-live-name-p2','tw-rmc-name-p2'].forEach(id => {
    const e = document.getElementById(id); if (e) e.textContent = p2name;
  });

  // Word scores
  const s1El = document.getElementById('tw-s1'); if (s1El) s1El.textContent = wordScores.player1 ?? 0;
  const s2El = document.getElementById('tw-s2'); if (s2El) s2El.textContent = wordScores.player2 ?? 0;

  // Section visibility
  document.getElementById('tw-prestart')?.classList.toggle('hidden', state !== 'waiting');
  document.getElementById('tw-active')  ?.classList.toggle('hidden', state === 'waiting' || state === 'ended');
  document.getElementById('tw-ended')   ?.classList.toggle('hidden', state !== 'ended');
  if (state === 'waiting' && btnTwStart) btnTwStart.disabled = false;

  if (state === 'active') {
    const scrambled = data.scrambled ?? TYPEWAVE_WORDS[wordIndex]?._localScramble ?? '——';
    const answer    = data.correctAnswer ?? TYPEWAVE_WORDS[wordIndex]?.answer ?? '——';
    const scrambledEl   = document.getElementById('tw-scrambled');
    const correctEl     = document.getElementById('tw-correct-answer');
    if (scrambledEl) scrambledEl.textContent = scrambled;
    if (correctEl)   correctEl.textContent   = `Answer: ${answer}`;

    // Re-establish host auto-advance if lost (e.g. host refreshed browser mid-round)
    if (!twWordTimerTimeout && data.wordEndTime && !wordWinner) {
      const remaining = data.wordEndTime - Date.now();
      if (remaining <= 0) {
        twAdvanceWord(wordIndex);
      } else {
        twWordTimerTimeout = setTimeout(() => twAdvanceWord(wordIndex), remaining);
      }
    }

    // Live answer cards
    [['p1','player1', p1name], ['p2','player2', p2name]].forEach(([p, pKey, pName]) => {
      const textEl  = document.getElementById(`tw-live-text-${p}`);
      const badgeEl = document.getElementById(`tw-live-badge-${p}`);
      const wrongEl = document.getElementById(`tw-wrong-${p}`);
      const cardEl  = document.getElementById(`tw-live-${p}`);

      const ans  = lastAnswer[pKey] ?? null;
      const wc   = wrongCounts[pKey] ?? 0;
      const won  = wordWinner === pKey;

      if (textEl)  textEl.textContent = ans ?? '—';
      if (wrongEl) wrongEl.textContent = wc > 0 ? `${wc} wrong (-${wc * 5} pts)` : '';

      if (won) {
        cardEl?.classList.add('tw-correct'); cardEl?.classList.remove('tw-wrong');
        if (badgeEl) { badgeEl.textContent = 'CORRECT ✓'; badgeEl.className = 'tw-live-badge tw-won'; badgeEl.classList.remove('hidden'); }
      } else if (ans && !won) {
        cardEl?.classList.remove('tw-correct'); cardEl?.classList.add('tw-wrong');
        if (badgeEl) { badgeEl.textContent = `WRONG ✗`; badgeEl.className = 'tw-live-badge tw-miss'; badgeEl.classList.remove('hidden'); }
      } else {
        cardEl?.classList.remove('tw-correct', 'tw-wrong');
        badgeEl?.classList.add('hidden');
      }
    });

    // Word winner banner
    const banner     = document.getElementById('tw-word-winner-banner');
    const bannerText = document.getElementById('tw-word-winner-text');
    const nextWordBtn= document.getElementById('btn-tw-next-word');
    if (wordWinner) {
      const wName = wordWinner === 'player1' ? p1name : p2name;
      if (bannerText) bannerText.textContent = `${wName} GOT IT! +1 WORD`;
      banner?.classList.remove('hidden');
      nextWordBtn?.classList.remove('hidden');
    } else {
      banner?.classList.add('hidden');
      nextWordBtn?.classList.add('hidden');
    }
  }

  if (state === 'ended') {
    const winner  = data.winner;
    const w1 = wordScores.player1 ?? 0;
    const w2 = wordScores.player2 ?? 0;
    const wc1= wrongCounts.player1 ?? 0;
    const wc2= wrongCounts.player2 ?? 0;
    const wName = winner === 'player1' ? p1name : winner === 'player2' ? p2name : null;

    const winnerEl = document.getElementById('tw-result-winner');
    const subEl    = document.getElementById('tw-result-sub');
    if (winnerEl) winnerEl.textContent = winner === 'tie' ? "IT'S A TIE!" : `${wName} WINS!`;
    if (subEl) {
      const wc1txt = wc1 > 0 ? ` (${wc1} wrong)` : '';
      const wc2txt = wc2 > 0 ? ` (${wc2} wrong)` : '';
      subEl.textContent = `${p1name}: ${w1} words${wc1txt} — ${p2name}: ${w2} words${wc2txt}`;
    }

    // Money deltas: base WIN/LOSE + wrong penalties
    let d1, d2;
    if (winner === 'player1') {
      d1 = _ctx.MONEY_EVENTS.TYPEWAVE_WIN  + wc1 * _ctx.MONEY_EVENTS.TYPEWAVE_WRONG;
      d2 = _ctx.MONEY_EVENTS.TYPEWAVE_LOSE + wc2 * _ctx.MONEY_EVENTS.TYPEWAVE_WRONG;
    } else if (winner === 'player2') {
      d1 = _ctx.MONEY_EVENTS.TYPEWAVE_LOSE + wc1 * _ctx.MONEY_EVENTS.TYPEWAVE_WRONG;
      d2 = _ctx.MONEY_EVENTS.TYPEWAVE_WIN  + wc2 * _ctx.MONEY_EVENTS.TYPEWAVE_WRONG;
    } else {
      d1 = wc1 * _ctx.MONEY_EVENTS.TYPEWAVE_WRONG;
      d2 = wc2 * _ctx.MONEY_EVENTS.TYPEWAVE_WRONG;
    }

    function twSetDelta(id, val) {
      const el = document.getElementById(id); if (!el) return;
      el.textContent = `${val >= 0 ? '+' : ''}${Math.abs(val)} pts`;
      el.className   = `rmc-delta ${val > 0 ? 'positive' : val < 0 ? 'negative' : 'neutral'}`;
    }
    twSetDelta('tw-delta-p1', d1);
    twSetDelta('tw-delta-p2', d2);

    document.getElementById('btn-tw-apply')?.classList.toggle('hidden', twLocal.resultApplied);
    document.getElementById('btn-tw-next-round')?.classList.toggle('hidden', !twLocal.resultApplied);
  }
}

// ── Render: player typewave ────────────────────────────────
export function renderPlayerTypewave(data) {
  if (!data || data.id !== 'typewave') return;

  const state      = data.state      ?? 'waiting';
  const wordIndex  = data.wordIndex  ?? 0;
  const wordScores = data.wordScores ?? { player1: 0, player2: 0 };
  const wordWinner = data.wordWinner ?? null;
  const myScore    = (_ctx.playerKey === 'player1' ? wordScores.player1 : wordScores.player2) ?? 0;

  document.getElementById('tw-p-waiting')?.classList.toggle('hidden', state !== 'waiting');
  document.getElementById('tw-p-active') ?.classList.toggle('hidden', state !== 'active');
  document.getElementById('tw-p-ended')  ?.classList.toggle('hidden', state !== 'ended');

  if (state !== 'active') { twStopClientTimer(); }

  if (state === 'active') {
    const scoreEl = document.getElementById('tw-p-my-score');
    if (scoreEl) scoreEl.textContent = myScore;

    // Use scrambled word from Firebase
    const scrambled   = data.scrambled ?? TYPEWAVE_WORDS[wordIndex]?._localScramble ?? '——';
    const scrambledEl = document.getElementById('tw-p-scrambled');
    if (scrambledEl) scrambledEl.textContent = scrambled;

    // Reset state when word changes
    if (twCurrentWordIndex !== wordIndex) {
      twCurrentWordIndex  = wordIndex;
      twAnsweredThisWord  = false;
      const input    = document.getElementById('tw-p-input');
      const statusEl = document.getElementById('tw-p-status');
      const submitBtn= document.getElementById('tw-p-submit');
      if (input)    { input.value = ''; input.disabled = false; input.className = ''; if (state === 'active') input.focus(); }
      if (statusEl) { statusEl.textContent = ''; statusEl.className = 'tw-p-status'; }
      if (submitBtn){ submitBtn.disabled = false; }
      // Start client-side timer using wordEndTime as source of truth
      const endTime = data.wordEndTime ?? (data.wordStartTime + TW_WORD_DURATION * 1000);
      if (endTime) twStartClientTimer(endTime);
    }

    // If word was won or timed out, disable input
    if (wordWinner && !twAnsweredThisWord) {
      const input    = document.getElementById('tw-p-input');
      const statusEl = document.getElementById('tw-p-status');
      const submitBtn= document.getElementById('tw-p-submit');
      if (input)    { input.disabled = true; }
      if (submitBtn){ submitBtn.disabled = true; }
      if (statusEl) {
        statusEl.textContent = wordWinner === _ctx.playerKey ? 'CORRECT! +1 WORD' : 'THEY GOT IT!';
        statusEl.className   = wordWinner === _ctx.playerKey ? 'tw-p-status tw-correct' : 'tw-p-status tw-neutral';
      }
      twStopClientTimer();
    }

    // Time's up — show message
    if (data.timedOut && !wordWinner) {
      const statusEl = document.getElementById('tw-p-status');
      const input    = document.getElementById('tw-p-input');
      const submitBtn= document.getElementById('tw-p-submit');
      if (statusEl) { statusEl.textContent = "TIME'S UP! Next word…"; statusEl.className = 'tw-p-status tw-neutral'; }
      if (input)    { input.disabled = true; }
      if (submitBtn){ submitBtn.disabled = true; }
      twStopClientTimer();
      twUpdateTimerRing(0);
    }
  }

  if (state === 'ended') {
    twStopClientTimer();
    const winner = data.winner;
    const ftEl   = document.getElementById('tw-p-final-text');
    if (ftEl) {
      if (winner === _ctx.playerKey) {
        ftEl.textContent = 'YOU WIN THE ROUND! +25 pts'; ftEl.className = 'rb-player-result-text won';
      } else if (winner === 'tie') {
        ftEl.textContent = "IT'S A TIE!"; ftEl.className = 'rb-player-result-text neutral';
      } else {
        ftEl.textContent = 'YOU LOSE THE ROUND. -15 pts'; ftEl.className = 'rb-player-result-text lost';
      }
    }
  }
}

// ── Player: submit typewave answer ─────────────────────────
async function submitTypewaveAnswer() {
  if (!_ctx.playerKey || !_ctx.getLatestRoundData() || _ctx.getLatestRoundData().id !== 'typewave') return;
  if (_ctx.getLatestRoundData().state !== 'active') return;
  if (twAnsweredThisWord) return;
  if (_ctx.getLatestRoundData().wordWinner != null) return; // word already claimed

  const input    = document.getElementById('tw-p-input');
  const statusEl = document.getElementById('tw-p-status');
  const submitBtn= document.getElementById('tw-p-submit');
  const answer   = input?.value.trim().toUpperCase();
  const correct  = _ctx.getLatestRoundData().correctAnswer?.toUpperCase();

  if (!answer) return;

  if (answer === correct) {
    twAnsweredThisWord = true;
    if (twClientTimerInterval) twStopClientTimer();
    if (input)    { input.disabled = true; input.classList.add('tw-inp-correct'); }
    if (submitBtn){ submitBtn.disabled = true; }
    if (statusEl) { statusEl.textContent = 'CORRECT! +1 WORD'; statusEl.className = 'tw-p-status tw-correct'; }

    const newScore    = (_ctx.getLatestRoundData().wordScores?.[_ctx.playerKey] ?? 0) + 1;
    const isRoundWin  = newScore >= 5;
    const updates     = {
      wordWinner:                        _ctx.playerKey,
      [`wordScores/${_ctx.playerKey}`]:  newScore,
      [`lastAnswer/${_ctx.playerKey}`]:  answer,
    };
    if (isRoundWin) { updates.state = 'ended'; updates.winner = _ctx.playerKey; }

    try {
      await _ctx.update(_ctx.ref(_ctx.db, 'round'), updates);
    } catch (err) { console.error('[Typewave] Correct submit error:', err); }

  } else {
    // Wrong — shake animation, cost -$5 later
    if (input) {
      input.classList.remove('tw-inp-wrong');
      void input.offsetWidth; // force reflow for animation restart
      input.classList.add('tw-inp-wrong');
      setTimeout(() => input.classList.remove('tw-inp-wrong'), 400);
    }
    const wc = (_ctx.getLatestRoundData().wrongCounts?.[_ctx.playerKey] ?? 0) + 1;
    if (statusEl) { statusEl.textContent = `WRONG! -5 pts (×${wc})`; statusEl.className = 'tw-p-status tw-wrong'; }

    try {
      await _ctx.update(_ctx.ref(_ctx.db, 'round'), {
        [`wrongCounts/${_ctx.playerKey}`]: wc,
        [`lastAnswer/${_ctx.playerKey}`]:  answer,
      });
    } catch (err) { console.error('[Typewave] Wrong submit error:', err); }
  }
}

// ── Module init — called from main.js ─────────────────────
export function init(ctx) {
  _ctx = ctx;

  // HOST: START TYPEWAVE
  btnTwStart = document.getElementById('btn-tw-start');
  if (btnTwStart) {
    btnTwStart.addEventListener('click', async () => {
      btnTwStart.disabled = true;
      twLocal = { resultApplied: false };
      if (twWordTimerTimeout) { clearTimeout(twWordTimerTimeout); twWordTimerTimeout = null; }
      const word      = TYPEWAVE_WORDS[0];
      const scrambled = _scrambleWord(word.answer);
      const now       = Date.now();
      try {
        _ctx.flashTransition('var(--pink)', 500);
        await _ctx.set(_ctx.ref(_ctx.db, 'round'), {
          id:            'typewave',
          state:         'active',
          wordIndex:     0,
          scrambled:     scrambled,
          correctAnswer: word.answer,
          wordWinner:    null,
          wordStartTime: now,
          wordEndTime:   now + TW_WORD_DURATION * 1000,
          timedOut:      false,
          wordScores:    { player1: 0, player2: 0 },
          wrongCounts:   { player1: 0, player2: 0 },
          lastAnswer:    { player1: null, player2: null },
          winner:        null,
          answers:       {}, stackerScores: {}, timer: 0, question: '',
        });
        // Host auto-advance timer
        twWordTimerTimeout = setTimeout(() => twAdvanceWord(0), TW_WORD_DURATION * 1000);
      } catch (err) {
        console.error('[Typewave] Start error:', err);
        btnTwStart.disabled = false;
      }
    });
  }

  // HOST: NEXT WORD (after someone wins a word)
  const btnTwNextWord = document.getElementById('btn-tw-next-word');
  if (btnTwNextWord) {
    btnTwNextWord.addEventListener('click', async () => {
      btnTwNextWord.classList.add('hidden');
      if (twWordTimerTimeout) { clearTimeout(twWordTimerTimeout); twWordTimerTimeout = null; }
      const curIdx = _ctx.getLatestRoundData()?.wordIndex ?? 0;
      await twAdvanceWord(curIdx);
    });
  }

  // HOST: SKIP WORD (force advance without scoring)
  const btnTwSkip = document.getElementById('btn-tw-skip-word');
  if (btnTwSkip) {
    btnTwSkip.addEventListener('click', async () => {
      if (twWordTimerTimeout) { clearTimeout(twWordTimerTimeout); twWordTimerTimeout = null; }
      const curIdx = _ctx.getLatestRoundData()?.wordIndex ?? 0;
      // Mark as timed out so players see "skip" message, then advance
      try {
        await _ctx.update(_ctx.ref(_ctx.db, 'round'), { timedOut: true });
        await new Promise(r => setTimeout(r, 800));
      } catch(e) {}
      await twAdvanceWord(curIdx);
    });
  }

  // HOST: APPLY RESULTS
  const btnTwApply = document.getElementById('btn-tw-apply');
  if (btnTwApply) {
    btnTwApply.addEventListener('click', async () => {
      if (twLocal.resultApplied) return;
      btnTwApply.disabled = true;
      twLocal.resultApplied = true;
      try {
        const [roundSnap, playersSnap] = await Promise.all([
          _ctx.get(_ctx.ref(_ctx.db, 'round')),
          _ctx.get(_ctx.ref(_ctx.db, 'players')),
        ]);
        const rd = roundSnap.val();
        const pd = playersSnap.val();

        const winner      = rd?.winner;
        const wrongCounts = rd?.wrongCounts ?? { player1: 0, player2: 0 };
        const wc1 = wrongCounts.player1 ?? 0;
        const wc2 = wrongCounts.player2 ?? 0;

        let d1, d2;
        if (winner === 'player1') {
          d1 = _ctx.MONEY_EVENTS.TYPEWAVE_WIN  + wc1 * _ctx.MONEY_EVENTS.TYPEWAVE_WRONG;
          d2 = _ctx.MONEY_EVENTS.TYPEWAVE_LOSE + wc2 * _ctx.MONEY_EVENTS.TYPEWAVE_WRONG;
        } else if (winner === 'player2') {
          d1 = _ctx.MONEY_EVENTS.TYPEWAVE_LOSE + wc1 * _ctx.MONEY_EVENTS.TYPEWAVE_WRONG;
          d2 = _ctx.MONEY_EVENTS.TYPEWAVE_WIN  + wc2 * _ctx.MONEY_EVENTS.TYPEWAVE_WRONG;
        } else {
          d1 = wc1 * _ctx.MONEY_EVENTS.TYPEWAVE_WRONG;
          d2 = wc2 * _ctx.MONEY_EVENTS.TYPEWAVE_WRONG;
        }

        if (!pd?.player1 || !pd?.player2) throw new Error('Missing player data');
        const newB1 = Math.max(0, Math.round((pd.player1.points ?? 0) + d1));
        const newB2 = Math.max(0, Math.round((pd.player2.points ?? 0) + d2));

        _ctx.flashTransition('var(--green)', 700);
        await _ctx.update(_ctx.ref(_ctx.db, 'players'), {
          'player1/points': newB1, 'player1/alive': newB1 > 0,
          'player2/points': newB2, 'player2/alive': newB2 > 0,
        });

        btnTwApply.classList.add('hidden');
        document.getElementById('btn-tw-next-round')?.classList.remove('hidden');
      } catch (err) {
        console.error('[Typewave] Apply error:', err);
        twLocal.resultApplied = false;
        btnTwApply.disabled = false;
      }
    });
  }

  // HOST: NEXT ROUND (3 → 4)
  const btnTwNextRound = document.getElementById('btn-tw-next-round');
  if (btnTwNextRound) {
    btnTwNextRound.addEventListener('click', async () => {
      btnTwNextRound.disabled = true;
      try {
        await _ctx.roundWipeTransition('ROUND 4');
        await _ctx.update(_ctx.ref(_ctx.db, 'game'), { currentRound: 4 });
      } catch (err) {
        console.error('[Typewave] Next round error:', err);
        btnTwNextRound.disabled = false;
      }
    });
  }

  // PLAYER: submit typewave answer
  if (_ctx.view === 'player') {
    const twInput  = document.getElementById('tw-p-input');
    const twSubmit = document.getElementById('tw-p-submit');
    if (twSubmit) twSubmit.addEventListener('click', submitTypewaveAnswer);
    if (twInput)  twInput.addEventListener('keydown', e => { if (e.key === 'Enter') submitTypewaveAnswer(); });
  }
}
